app:
  title: "Process Dashboard"
  description: "A clean and extensible Streamlit application for internal process management"
  version: "1.0.0"

categories:
  weekly_production:
    name: "Weekly Production"
    description: "Analyze and report weekly production data"
    icon: "📅"
    processes:
      - weekly_production_analyzer
    process_names:
      weekly_production_analyzer: "Weekly Production Analyzer"
    process_descriptions:
      weekly_production_analyzer: "Analyze weekly production data using external package logic"

ui:
  theme:
    primary_color: "#FF6B6B"
    background_color: "#FFFFFF"
    secondary_background_color: "#F0F2F6"
    text_color: "#262730"
  
  layout:
    sidebar_width: 300
    max_width: 1200
    padding: 20

features:
  enable_logging: true
  enable_error_tracking: true
  enable_analytics: false
  cache_timeout: 3600 